services:
  db: 
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password1234 
      MYSQL_DATABASE: my_fastapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:  # 포트 포워딩 (내 컴퓨터 포트: 컨테이너 내부 포트)
      - "3307:3306" 
    volumes:  # 데이터 영속성 설정 (내 컴퓨터 폴더: 컨테이너 내부 폴더 ) 
      - ./mysql_data:/var/lib/mysql